apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rekbers
      service: auth
  template:
    metadata:
      labels:
        app: rekbers
        service: auth
        sidecar.istio.io/inject: "true"
        version: "1"
    spec:
      imagePullSecrets:
        - name: ghcr
      containers:
      - name: auth
        image: ghcr.io/wofood/rekbers_auth
        resources:
          requests:
            memory: "500Mi"
            cpu: "250m"
          limits:
            memory: "1G"
            cpu: "500m"
        ports:
          - name: auth
            protocol: TCP
            containerPort: 3000
        envFrom:
          - configMapRef:
              name: rekbers-config
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 3
          periodSeconds: 3
          failureThreshold: 2
