apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: admins-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: admins-depl
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
